kind: Secret
apiVersion: v1
metadata:
  name: wmagent-trace-secrets
type: Opaque
stringData:
  stompserverconfig4fwjr.json: |+
    {
    "stompLogin": "{{ .Values.wmagentBroker.stompLogin }}",
    "stompPassword": "{{ .Values.wmagentBroker.stompPassword }}",
    "producer": "wmarchive",
    "endpointConsumer": "/topic/cms.jobmon.wmarchive",
    "endpointProducer": "/topic/cms.rucio.tracer",
    "stompURIProducer": "{{ .Values.wmagentBroker.stompURIProducer }}",
    "stompURIConsumer": "{{ .Values.wmagentBroker.stompURIConsumer }}",
    "interval": 1,
    "verbose": 2,
    "Protocol": "tcp4",
    "port": {{ .Values.monitoring.promPort }},
    "stompSendTimeout": 5000,
    "stompRecvTimeout": 5000
    }
