kind: Secret
apiVersion: v1
metadata:
  name: xrootd-trace-secrets
type: Opaque
stringData:
  stompserverconfig4xrtd.json: |+
    {
    "stompLogin": "{{ .Values.cmsswPopBroker.stompLogin }}",
    "stompPassword": "{{ .Values.cmsswPopBroker.stompPassword }}",
    "producer": "xrootd",
    "endpointConsumer": "/topic/xrootd.cms.aaa.ng",
    "endpointProducer": "/topic/cms.rucio.tracer",
    "stompURIProducer": "{{ .Values.cmsswPopBroker.stompURIProducer }}",
    "stompURIConsumer": "{{ .Values.cmsswPopBroker.stompURIConsumer }}",
    "interval": 3,
    "verbose": 2,
    "Protocol": "tcp4",
    "port": {{ .Values.monitoring.promPort }},
    "stompSendTimeout": 5000,
    "stompRecvTimeout": 5000
    }
