apiVersion: v1
kind: ConfigMap
metadata:
  name: statsd-exporter-configmap
  labels:
    app: statsd-exporter
data:
  statsd_mapping.yaml: |-
    mappings:
{{ toYaml .Values.mappings | indent 6 }}
    defaults:
      ttl: {{ .Values.ttl }}
