apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rucio-statsd-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rucio-statsd-exporter.name" . }}
    helm.sh/chart: {{ include "rucio-statsd-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rucio-statsd-exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rucio-statsd-exporter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      volumes:
        - name: statsd-configmap
          configMap:
            name: statsd-exporter-configmap
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: export
              containerPort: 9102
            - name: import
              containerPort: 9125
              protocol: UDP
          volumeMounts:
            - name: statsd-configmap
              subPath: statsd_mapping.yaml
              mountPath: /tmp/statsd_mapping.yaml
          args: [
            "--statsd.mapping-config=/tmp/statsd_mapping.yaml"
          ]
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
