apiVersion: v1
kind: Service
metadata:
  name: {{ include "rucio-statsd-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rucio-statsd-exporter.name" . }}
    helm.sh/chart: {{ include "rucio-statsd-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: import
      port: 8125 #port to push metrics to
      protocol: UDP
      targetPort: import
    - name: export
      port: 9102 #port to fetch metrics from
      protocol: TCP
      targetPort: export
  selector:
    app.kubernetes.io/name: {{ include "rucio-statsd-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
