{{- if .Values.reportStorageClass.osShareID }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rucio-consistency-sc
provisioner: manila-provisioner
parameters:
  type: "Meyrin CephFS"
  zones: nova
  osSecretName: os-trustee
  osSecretNamespace: kube-system
  protocol: CEPHFS
  backend: csi-cephfs
  csi-driver: cephfs.csi.ceph.com
  osShareID: {{ .Values.reportStorageClass.osShareID }} 
  osShareAccessID: {{ .Values.reportStorageClass.osShareAccessID }} 
{{- end }}


