apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rucio-consistency.fullname" . }}-unmerged-config
data:
  config.yaml: |+
    rses:
      "*": # default
        ignore_list:
          - /store/unmerged/logs
          - /store/unmerged/SAM/testSRM
        preprocess:
          filter:     "/store/unmerged/"
        scanner:
          recursion:      1
          nworkers:        8
          timeout:        180
{{- if  (.Values.consistency.filter) }}
          filter: {{ .Values.consistency.filter }}
{{- end }}
          server_root: {{.Values.consistency.defaultRoot }}
          remove_prefix: /
          add_prefix: /
          roots: 
          - path: /store/unmerged

{{ range $site, $config := .Values.consistency.sites }}
      {{ $site }}:
{{- if $config }}
{{- if or (or $config.server $config.server_root) $config.timeout }}
        scanner:
{{- if  ($config.server) }}
          server: {{ $config.server }}
{{- end }}
{{- if  ($config.server_root) }}
          server_root: {{ $config.server_root }}
{{- end }}
{{- if  ($config.timeout) }}
          timeout: {{ $config.timeout }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
